"""
Fastag Fraud Detection - Training Pipeline (Fixed)
====================================================
Fixes applied vs. the original notebook:

1. Stratified train/test split -> preserves the fraud ratio in both sets.
2. LabelEncoders are fit ONLY on the training data (no leakage from the test
   set). Any category not seen during training maps to a safe "unknown"
   bucket at inference time instead of crashing the app.
3. Class imbalance is actually handled: class_weight='balanced' for models
   that support it, sample_weight for GradientBoosting (which has no
   class_weight parameter), instead of being ignored.
4. Models are compared on precision / recall / F1 for the FRAUD class
   specifically (computed live), not on plain accuracy, and not on
   hand-typed numbers.
5. The model saved to disk is the exact object that was evaluated (trained
   on x_train only) -- so the metrics you see are the metrics of what you
   actually deploy. Nothing is silently retrained-and-reshipped afterward.
6. Label encoders, the target encoder, and the exact training column order
   are all saved to disk, so app.py loads them instead of hand-typing
   category -> integer maps that can silently drift out of sync.
7. Removed the Payment_Diff / Payment_Ratio engineered features. Analysis on
   the real dataset showed Fraud_indicator is generated by an exact rule
   (Fraud iff Transaction_Amount != Amount_paid, with zero exceptions across
   all 5000 rows) -- so those derived features didn't help the model learn
   fraud patterns, they just handed it the label-generation formula, which
   is why several models hit an unrealistic 100% F1. Transaction_Amount and
   Amount_paid are still included as raw features (they're genuinely part of
   the dataset), but no longer pre-combined into a feature that's a 1:1
   encoding of the answer.

Run this once to produce:
    fastag_fraud_model.pkl
    label_encoders.pkl
    target_encoder.pkl
    feature_columns.pkl
Then run app.py (also fixed) which loads these four files.
"""

import numpy as np
import pandas as pd
import joblib

from sklearn.base import clone
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.utils.class_weight import compute_sample_weight
from sklearn.metrics import make_scorer
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (
    classification_report, confusion_matrix, accuracy_score,
    precision_score, recall_score, f1_score, roc_auc_score,
)

RANDOM_STATE = 42

# ---------------------------------------------------------------------------
# 1. Load data
# ---------------------------------------------------------------------------
df = pd.read_csv("FastagFraudDetection.csv")

# ---------------------------------------------------------------------------
# 2. Feature engineering (same as the original notebook, plus two additions)
# ---------------------------------------------------------------------------
df["state_code"] = df["Vehicle_Plate_Number"].str[:2]
df.drop(columns=["Vehicle_Plate_Number"], inplace=True)

df["Timestamp"] = pd.to_datetime(df["Timestamp"])
df["Hour"] = df["Timestamp"].dt.hour
df["Day_of_Week"] = df["Timestamp"].dt.dayofweek
df["Month"] = df["Timestamp"].dt.month
df.drop(columns=["Timestamp"], inplace=True)

df.drop(columns=["Transaction_ID", "FastagID", "Geographical_Location"], inplace=True)

# REMOVED: Payment_Diff / Payment_Ratio. Fraud_indicator in this dataset is
# generated by an exact rule (Fraud iff Transaction_Amount != Amount_paid,
# confirmed with zero exceptions across all 5000 rows). Deriving a feature
# that's a 1:1 encoding of that rule doesn't teach the model anything --
# it just leaks the answer, which is why Decision Tree / Random Forest /
# Gradient Boosting all hit an unrealistic 100% F1 with it included.
# Transaction_Amount and Amount_paid stay in as raw features below.

categorical_cols = ["Vehicle_Type", "Lane_Type", "Vehicle_Dimensions",
                     "TollBoothID", "state_code"]
target_col = "Fraud_indicator"

X = df.drop(columns=[target_col])
y_raw = df[target_col]

# Target encoding: fit on the full label set (only 2 fixed classes, no
# leakage concern the way per-row features have).
target_encoder = LabelEncoder()
y = target_encoder.fit_transform(y_raw)
print("Target classes:", list(target_encoder.classes_),
      "-> codes", list(range(len(target_encoder.classes_))))

# ---------------------------------------------------------------------------
# 3. FIX: stratified split, done BEFORE fitting any categorical encoders
# ---------------------------------------------------------------------------
x_train, x_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=RANDOM_STATE, stratify=y
)

# FIX: fit each LabelEncoder on x_train only. Unseen categories (in x_test,
# or later at inference time in the Streamlit app) map to a reserved
# "unknown" code instead of raising a KeyError.
label_encoders = {}
for col in categorical_cols:
    x_train[col] = x_train[col].astype(str)
    x_test[col] = x_test[col].astype(str)

    le = LabelEncoder()
    le.fit(x_train[col])
    class_to_code = {cls: code for code, cls in enumerate(le.classes_)}
    unknown_code = len(class_to_code)  # reserved for categories not seen in training

    x_train[col] = x_train[col].map(class_to_code)
    x_test[col] = x_test[col].map(class_to_code).fillna(unknown_code).astype(int)

    label_encoders[col] = {"class_to_code": class_to_code, "unknown_code": unknown_code}

feature_columns = list(x_train.columns)  # exact order app.py must replicate

# ---------------------------------------------------------------------------
# 4. FIX: class-imbalance-aware model comparison with real, live metrics
# ---------------------------------------------------------------------------
sample_weight_train = compute_sample_weight(class_weight="balanced", y=y_train)
FRAUD_CODE = int(np.where(target_encoder.classes_ == "Fraud")[0][0])


def evaluate_model(name, y_true, y_pred, y_score=None):
    result = {
        "model": name,
        "accuracy": accuracy_score(y_true, y_pred),
        "precision_fraud": precision_score(y_true, y_pred, pos_label=FRAUD_CODE),
        "recall_fraud": recall_score(y_true, y_pred, pos_label=FRAUD_CODE),
        "f1_fraud": f1_score(y_true, y_pred, pos_label=FRAUD_CODE),
    }
    if y_score is not None:
        # FIX: roc_auc_score treats the numerically larger label (1 = "Not
        # Fraud" in our encoding) as positive by default. We care about
        # ranking the FRAUD class, so relabel explicitly: 1 = Fraud, 0 =
        # everything else, and score against the fraud-class probability.
        y_true_fraud = (np.asarray(y_true) == FRAUD_CODE).astype(int)
        result["roc_auc_fraud"] = roc_auc_score(y_true_fraud, y_score)
    print(f"\n--- {name} ---")
    print(classification_report(y_true, y_pred, target_names=list(target_encoder.classes_)))
    print("Confusion matrix:\n", confusion_matrix(y_true, y_pred))
    return result


candidates = {
    "Logistic Regression": LogisticRegression(max_iter=1000, class_weight="balanced"),
    "Decision Tree": DecisionTreeClassifier(class_weight="balanced", random_state=RANDOM_STATE),
    "Random Forest": RandomForestClassifier(class_weight="balanced", random_state=RANDOM_STATE),
    "Gradient Boosting": GradientBoostingClassifier(random_state=RANDOM_STATE),  # no class_weight arg
    "SVM": SVC(class_weight="balanced", probability=True, random_state=RANDOM_STATE),
    "KNN": KNeighborsClassifier(),  # no native class-weighting option
}

results, fitted_models = [], {}
for name, model in candidates.items():
    if name == "Gradient Boosting":
        model.fit(x_train, y_train, sample_weight=sample_weight_train)
    else:
        model.fit(x_train, y_train)

    y_pred = model.predict(x_test)
    y_score = model.predict_proba(x_test)[:, FRAUD_CODE] if hasattr(model, "predict_proba") else None
    results.append(evaluate_model(name, y_test, y_pred, y_score))
    fitted_models[name] = model

results_df = pd.DataFrame(results)

# ---------------------------------------------------------------------------
# 4b. FIX: don't trust a single test split to break ties. If several models
#     land at or near a perfect fraud-F1, that's a red flag for a leaky
#     feature more than a sign they're all great -- run 5-fold CV on the
#     training data so the "winner" reflects consistent performance across
#     folds, not one favorable split.
# ---------------------------------------------------------------------------
fraud_f1_scorer = make_scorer(f1_score, pos_label=FRAUD_CODE)
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)

cv_rows = []
for name, model in candidates.items():
    cv_model = clone(model)  # fresh, unfit copy -- CV must not reuse fitted state
    scores = cross_val_score(cv_model, x_train, y_train, cv=cv, scoring=fraud_f1_scorer)
    cv_rows.append({"model": name, "cv_f1_fraud_mean": scores.mean(), "cv_f1_fraud_std": scores.std()})
    print(f"{name:22s} 5-fold CV fraud-F1: {scores.mean():.3f} (+/- {scores.std():.3f})  folds={np.round(scores, 3)}")

cv_df = pd.DataFrame(cv_rows)
results_df = results_df.merge(cv_df, on="model")
results_df = results_df.sort_values(["cv_f1_fraud_mean", "f1_fraud"], ascending=False)

print("\n=== Model comparison (sorted by cross-validated fraud-F1, then test-set fraud-F1) ===")
print(results_df.to_string(index=False))

top_cv_score = results_df.iloc[0]["cv_f1_fraud_mean"]
near_perfect = results_df[results_df["cv_f1_fraud_mean"] >= 0.999]
if len(near_perfect) > 0:
    print(
        f"\n⚠️  {len(near_perfect)} model(s) scored ~1.00 fraud-F1 across CV folds: "
        f"{list(near_perfect['model'])}. Real-world fraud detection is essentially "
        "never perfectly separable -- check the feature-importance printout below. "
        "If Transaction_Amount/Amount_paid dominate, remember this dataset defines "
        "Fraud_indicator as an exact rule on those two columns, so a model finding "
        "it isn't learning a subtle pattern -- it's finding the label formula."
    )

# ---------------------------------------------------------------------------
# 5. FIX: save the SAME model object that was just evaluated (no silent
#    retrain-on-everything step that would make the reported metrics stale)
# ---------------------------------------------------------------------------
best_name = results_df.iloc[0]["model"]
best_model = fitted_models[best_name]
print(f"\nSelected model: {best_name} "
      f"(CV fraud-F1={results_df.iloc[0]['cv_f1_fraud_mean']:.3f}, "
      f"test fraud-F1={results_df.iloc[0]['f1_fraud']:.3f}, "
      f"test recall-fraud={results_df.iloc[0]['recall_fraud']:.3f})")

# Diagnostic: which features is the winning model actually relying on?
if hasattr(best_model, "feature_importances_"):
    importances = pd.Series(best_model.feature_importances_, index=feature_columns)
    importances = importances.sort_values(ascending=False)
    print("\nFeature importances (top 5) -- check whether Transaction_Amount/Amount_paid dominate:")
    print(importances.head(5).to_string())
elif hasattr(best_model, "coef_"):
    coefs = pd.Series(best_model.coef_[0], index=feature_columns).sort_values(key=abs, ascending=False)
    print("\nModel coefficients (top 5 by magnitude) -- check whether Transaction_Amount/Amount_paid dominate:")
    print(coefs.head(5).to_string())

joblib.dump(best_model, "fastag_fraud_model.pkl")
joblib.dump(label_encoders, "label_encoders.pkl")
joblib.dump(target_encoder, "target_encoder.pkl")
joblib.dump(feature_columns, "feature_columns.pkl")

print("\nSaved: fastag_fraud_model.pkl, label_encoders.pkl, "
      "target_encoder.pkl, feature_columns.pkl")